[project]
name = "recon-gh"
version = "0.1.0"
description = "Recon is a powerful CLI companion for developers and tools for agents, turning GitHub activity and repository data into useful insights from your terminal"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "rich-pixels>=3.0.1",
    "typer>=0.27.1",
]

[dependency-groups]
dev = [
    "build>=1.3.0",
    "pyright>=1.1.400",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.0",
    "ruff>=0.12.0",
]